### ISSUE TITLE
 Can you help me with using  SSH in simple+?

### ISSUE THREAD

**Issue by maxlee365** [bitm0de/HttpsUtility#2]
Did the had example of ssh Control？or can you gave me some idea. Thanks a lot

**Comment by bitm0de** [comment]
@maxlee365 - This is not the place for these types of questions. The Issues section on github is mainly intended for issues pertaining to the repo and its source code. SSH is not applicable to HTTPS or this HttpsUtility module.

Issues are normally used to keep track of bugs, enhancements, or other requests relating to the project in the repo. [https://help.github.com/en/github/site-policy/github-community-guidelines](url)

> Be clear and stay on topic - People use GitHub to get work done and to be more productive. Off-topic comments are a distraction (sometimes welcome, but usually not) from getting work done and being productive. Staying on topic helps produce positive and productive discussions.
