### ISSUE TITLE
Wrong encoding in the response

### ISSUE THREAD

**Issue by sergiowebsphere** [bitm0de/HttpsUtility#6]
Hi Troy, hope you are doing well.

I have a question. 
I'm calling a REST API, and the response is displaying with the wrong encoding.
The response I'm receiving is for example: `{"name":"Mar??a"}` instead of `{"name":"María"}`.
When I test it in POSTMAN, I'm receiving the response in the correct encoding.
Is this an error? or I'm missing something?
Thanks.

![Response2](https://user-images.githubusercontent.com/37790146/156705981-6b8b286e-d487-442d-970c-e495aae88da2.jpeg)

**Comment by bitm0de** [comment]
There's no encoding conversions within the module itself. If you're dealing with Unicode then you may have to set all the appropriate encoding directives and flags for your program and the modules themselves. That likely isn't supported by default, since Crestron supports ASCII and UTF16LE.
